from typing import Any

class Field:
    def __init__(self, read_only: bool = False, write_only: bool = False, required: bool | None = None, default: Any = ..., source: str | None = None, **kwargs: Any) -> None: ...

class CharField(Field): ...
class IntegerField(Field): ...
class FloatField(Field): ...
class BooleanField(Field): ...
class DecimalField(Field): ...
class DateTimeField(Field): ...
class DateField(Field): ...
class TimeField(Field): ...
class UUIDField(Field): ...
class EmailField(Field): ...
class URLField(Field): ...
class SlugField(Field): ...
class ListField(Field): ...
class DictField(Field): ...
class JSONField(Field): ...
class SerializerMethodField(Field): ...
class ReadOnlyField(Field): ...
class HiddenField(Field): ...
class FileField(Field): ...
class ImageField(Field): ...
class IPAddressField(Field): ...
class ChoiceField(Field): ...
class MultipleChoiceField(Field): ...
class RegexField(Field): ...
class DurationField(Field): ...
