from typing import Any

from fastrest.request import Request

class GenericAPIView:
    queryset: type | None
    serializer_class: type | None
    lookup_field: str
    lookup_url_kwarg: str | None
    lookup_field_type: type
    dependencies: list[Any]
    request: Request
    action: str
    kwargs: dict[str, Any]
    _session: Any

    def get_session(self) -> Any: ...
    def set_session(self, session: Any) -> None: ...
    def get_queryset(self) -> Any: ...
    def get_object(self) -> Any: ...
    def get_serializer(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_serializer_class(self) -> type: ...
    def get_serializer_context(self) -> dict[str, Any]: ...
    async def initial(self, request: Request, **kwargs: Any) -> None: ...
