from typing import Any

class BasePermission:
    def has_permission(self, request: Any, view: Any) -> bool: ...
    def has_object_permission(self, request: Any, view: Any, obj: Any) -> bool: ...

class AllowAny(BasePermission): ...
class IsAuthenticated(BasePermission): ...
class IsAdminUser(BasePermission): ...
class IsAuthenticatedOrReadOnly(BasePermission): ...

class HasScope(BasePermission):
    def __init__(self, *scopes: str) -> None: ...
