"""remove_client_id_secret_token_uri_from_external_account

Revision ID: 56b7bec71b09
Revises: c869d602a748
Create Date: 2026-04-02 07:59:41.547664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56b7bec71b09'
down_revision: Union[str, Sequence[str], None] = 'c869d602a748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_account', 'client_secret')
    op.drop_column('external_account', 'client_id')
    op.drop_column('external_account', 'token_uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_account', sa.Column('token_uri', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('external_account', sa.Column('client_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('external_account', sa.Column('client_secret', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
