"""initial schema

Revision ID: 5e169cfae984
Revises:
Create Date: 2026-03-08 11:17:49.300887

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from underway.models.types import MySQLUUID

# revision identifiers, used by Alembic.
revision: str = "5e169cfae984"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", MySQLUUID(length=16), nullable=False),
        sa.Column("app_login", sa.String(length=120), nullable=False),
        sa.Column("ai_api_key", sa.String(length=255), nullable=True),
        sa.Column("ai_instructions", sa.Text(), nullable=True),
        sa.Column("schedule_slot_duration", sa.Integer(), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_user_app_login"), "app_user", ["app_login"], unique=True)
    op.create_table(
        "conversation",
        sa.Column("id", MySQLUUID(length=16), nullable=False),
        sa.Column("user_id", MySQLUUID(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "external_account",
        sa.Column("id", MySQLUUID(length=16), nullable=False),
        sa.Column("external_email", sa.String(length=255), nullable=False),
        sa.Column("user_id", MySQLUUID(length=16), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("token", sa.Text(), nullable=True),
        sa.Column("api_key", sa.String(length=255), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("token_uri", sa.String(length=255), nullable=True),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("client_secret", sa.String(length=255), nullable=True),
        sa.Column("scopes", sa.Text(), nullable=True),
        sa.Column("write_calendar", sa.Boolean(), nullable=False),
        sa.Column("write_tasks", sa.Boolean(), nullable=False),
        sa.Column("use_for_calendar", sa.Boolean(), nullable=False),
        sa.Column("use_for_tasks", sa.Boolean(), nullable=False),
        sa.Column("needs_reauth", sa.Boolean(), nullable=False),
        sa.Column("last_sync", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", MySQLUUID(length=16), nullable=False),
        sa.Column("user_id", MySQLUUID(length=16), nullable=False),
        sa.Column("task_user_email", sa.String(length=255), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_task_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.String(length=255), nullable=True),
        sa.Column("project_name", sa.String(length=255), nullable=True),
        sa.Column("parent_id", sa.String(length=255), nullable=True),
        sa.Column("section_id", sa.String(length=255), nullable=True),
        sa.Column("list_type", sa.String(length=50), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("last_synced", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "task_user_email",
            "provider",
            "provider_task_id",
            name="uq_user_id_task_user_provider_task",
        ),
    )
    op.create_index(op.f("ix_tasks_task_user_email"), "tasks", ["task_user_email"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_table(
        "chat_message",
        sa.Column("id", MySQLUUID(length=16), nullable=False),
        sa.Column("conversation_id", MySQLUUID(length=16), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=255), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_message")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_task_user_email"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("external_account")
    op.drop_table("conversation")
    op.drop_index(op.f("ix_app_user_app_login"), table_name="app_user")
    op.drop_table("app_user")
    # ### end Alembic commands ###
