"""add_oauth_state_table

Revision ID: 767105043a33
Revises: 56b7bec71b09
Create Date: 2026-04-02 08:04:06.191634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '767105043a33'
down_revision: Union[str, Sequence[str], None] = '56b7bec71b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_state',
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('user_id', mysql.BINARY(length=16), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_state')
    # ### end Alembic commands ###
